# Training hyperparameters

FREQ_TRESHOLD = 5
LEARNING_RATE = 0.00001
BATCH_SIZE = 32
NUM_EPOCHS = 100
NUM_CHANNELS = 3
IMAGE_HEIGHT = 128
IMAGE_WIDTH = 128
PATCH_SIZE = 8
HIDDEN_SIZE = 192
NUM_LAYER = (6, 6) # Number of Transformer blocks for the (Encoder, Decoder)
NUM_HEADS = 8

EMBEDDING_DIM = 560
PIN_MEMORY = True
LOAD_MODEL = True

DROPOUT = 0.02
MLP_SIZE = 3072
NUM_TRANSFORMER_LAYER = 12


NUM_WORKERS = 4
# Compute related
ACCELERATOR = "gpu"
DEVICES = [0]
PRECISION = 16
