BATCH_SIZE = 6
TRAIN_EPOCH = 100
LR = 2e-5
TIMESTEPS = 500

DATASET_ROOT = "latent_output"  
IMAGE_DIR = 'images'

LOAD_MODEL = True
CHECKPOINT_PATH = 'final_vgg226.pt' 


IMAGE_SIZE = 12 
CHANNELS_IN = 4  
PATCH_SIZE = 2  
HIGHRES_PATCH_SIZE = 1  
HIDDEN_SIZE = 420  
NUM_FEATURES = 256  
NUM_LAYERS = 16
NUM_HEADS = 12